server:
  port: ${PORT:3003}

spring:
  application:
    name: pe-sub-jobs
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pesub}
    username: ${SPRING_DATASOURCE_USERNAME:pesub}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  threads:
    virtual:
      enabled: true

ingest:
  facility-file: ${FACILITY_INGEST_FILE:data/mock/facilities.csv}
  lp-master-file: ${LP_MASTER_INGEST_FILE:data/mock/lp_master.csv}
  lp-facility-seeds-file: ${LP_FACILITY_SEEDS_FILE:data/mock/lp_facility_seeds.csv}

logging:
  file:
    path: ${LOG_PATH:C:/Users/alexl/apps/pe-sub/logs}
