#!/usr/bin/env python3
r"""
LP DB Export *generator* (one-off dev utility; companion to lp_db_extract.py).

The original pe-sub-jobs/data/import/LP DB Export was randomly generated by another agent and is
defective: it padded ~1,518 real (facility, investor) positions with ~13x duplicate rows (same LP,
same facility, contradictory financials) to reach 20,000 rows. Run through the extract those
collapse back to ~1,518 lp_records.

This script regenerates a CLEAN export that yields ~20,000 *distinct* lp_records, matching the real
data shape the product owner described:
  * LPs are NOT unique — each distinct LP holds a position in 4-12 DIFFERENT facilities
    (repeats span facilities; an LP appears at most once per facility, respecting the
    lp_records (facility, investor) grain and the API's dedup).
  * Facilities ARE the unique key. We reuse the 68 real facilities from data/mock/facilities.csv,
    plus 2 orphan accounts (not in facilities.csv) so the extract's "Unknown" placeholder path
    still runs.
  * Each LP's identity/classification/ratings/scale/UBS-credit-profile attributes are CONSTANT
    across all its rows (the defect was randomizing these per row). Only the facility-specific
    financials (commitment, called/uncalled, BB) vary by position.
  * Values use the canonical Investor Type / Agent LP Category / UBS advance-rate tiers from
    data/reference/, so the extract's unmatched-dumps come back empty.

Output: overwrites data/import/<EXPORT_NAME> (the same file lp_db_extract.py reads). Re-run the
extract afterwards to produce the seed CSVs.

NO command-line arguments — tune the constants below and re-run.
"""
from __future__ import annotations

import csv
import random
from datetime import date, timedelta
from pathlib import Path

import openpyxl

SCRIPT_DIR = Path(__file__).resolve().parent          # pe-sub-jobs/data/
FACILITIES_FILE = SCRIPT_DIR / "mock" / "facilities.csv"
EXPORT_OUT = SCRIPT_DIR / "import" / "LP DB Export 2026.06.25.xlsx"
SHEET_NAME = "_BBs20260625"

# ── tunables ────────────────────────────────────────────────────────────────
SEED = 20260625
TARGET_ROWS = 20_000            # distinct lp_records to produce
REPEAT_MIN, REPEAT_MAX = 4, 12  # facilities each LP participates in
ORPHAN_ACCOUNTS = [             # AccountIDs NOT in facilities.csv -> exercise "Unknown" path
    ("5VZ9001", "TPG AG Asset Based Credit Fund"),
    ("5VZ9002", "TPG AG Asset Based Credit Fund"),
]

# Column order MUST match lp_db_extract.SRC_COLS exactly (the extract validates the header).
SRC_COLS = [
    "AccountID", "FndName", "InvestorName", "Parent", "SPV", "InvestorType", "Region", "HQ",
    "InstitutionalHNW", "InvestmentGrade", "Classification", "Notes", "SP", "Moodys", "Fitch",
    "AUM", "NAV", "PensionAssets", "FundingRatio", "UBSAR", "AgentAR", "Commitments",
    "PercentOfCommitments", "Called", "Uncalled", "PercentOfUncalled", "CalledPercent",
    "AgentCL", "UBSCL", "AgentBB", "UBSBB", "BBDate",
]

# ── reference vocabularies (canonical -> map cleanly through the extract) ─────
REGIONS = ["North America", "Europe", "Asia Pacific", "Latin America", "Middle East",
           "United Kingdom", "Africa"]

# investor_type -> (name-suffix templates, size-measure). Canonical per data/reference/investor_types.csv.
TYPE_SPECS = {
    "Public Pension":        (["Public Employees Retirement System", "State Teachers Retirement", "State Pension Fund"], "pension"),
    "Pension Fund":          (["Pension Fund", "Retirement Trust", "Pension Scheme"], "pension"),
    "Endowment":             (["University Endowment", "Endowment Fund", "College Endowment"], "aum"),
    "Foundation":            (["Foundation", "Charitable Foundation", "Family Foundation"], "aum"),
    "Family Office":         (["Family Office", "Family Capital", "Family Holdings"], "aum"),
    "Insurance Company":     (["Life Insurance Co.", "Mutual Insurance", "Assurance Group"], "aum"),
    "Sovereign Wealth Fund": (["Investment Authority", "Sovereign Fund", "Future Fund"], "aum"),
    "Fund of Funds":         (["Fund of Funds", "Multi-Manager Fund", "Partners Fund"], "nav"),
    "Hedge Fund":            (["Master Fund", "Absolute Return Fund", "Opportunities Fund"], "nav"),
    "Endowment ":            (["Endowment"], "aum"),
    "Corporate":             (["Treasury", "Corporate Holdings", "Group Treasury"], "aum"),
    "Healthcare":            (["Health System", "Hospital Trust", "Healthcare Endowment"], "aum"),
    "Investment Consultant": (["Investment Advisors", "Capital Advisors", "Consulting Group"], "aum"),
    "Institutional Investor":(["Institutional Trust", "Alternative Assets Trust", "Capital Partners"], "aum"),
    "Other Institutional":   (["Strategic Capital Partners", "Alternative Assets", "Global Investors"], "aum"),
}
TYPE_WEIGHTS = {  # rough real-world mix
    "Public Pension": 16, "Pension Fund": 14, "Insurance Company": 12, "Endowment": 9,
    "Foundation": 8, "Sovereign Wealth Fund": 6, "Family Office": 8, "Fund of Funds": 7,
    "Hedge Fund": 4, "Corporate": 4, "Healthcare": 3, "Investment Consultant": 2,
    "Institutional Investor": 3, "Other Institutional": 4,
}

# Agent LP Category (export "Classification") -> BUSA agent advance rate. Canonical RHS of
# data/reference/agent_lp_categories.csv, so it maps to itself (no unmatched).
AGENT_CATEGORIES = [
    ("Rated Included",            0.90, 30),
    ("Non-Rated Included",        0.75, 34),
    ("Designated Institutional",  0.65, 18),
    ("Designated PWM",            0.50, 10),
    ("Ineligible Investor",       0.00,  8),
]

# UBS classification tiers (min advance rate) — the SAME tiers Run Shadow BB uses. We pick a UBSAR
# inside a band; the extract derives ubs_classification from it. (band_lo, band_hi, weight)
UBS_BANDS = [
    (0.90, 0.97, 28),   # Rated Investor
    (0.75, 0.90, 26),   # Unrated NAV > $1Bn
    (0.65, 0.75, 20),   # Corp Pension > $5Bn
    (0.50, 0.65, 16),   # Other Institutional
    (0.30, 0.50, 10),   # Excluded
]

IG_RATINGS   = ["AAA", "AA+", "AA", "AA-", "A+", "A", "A-", "BBB+", "BBB", "BBB-"]
NONIG_RATINGS = ["BB+", "BB", "BB-", "B+", "B", "NR"]

WORD1 = ["Apex", "Meridian", "Granite", "Harborview", "Ironwood", "Cascade", "Dominion", "Everest",
         "Fairview", "Northgate", "Oakmont", "Pinnacle", "Redwood", "Silverpeak", "Trident", "Union",
         "Westbridge", "Yorkshire", "Zenith", "Brookstone", "Cedar", "Kestrel", "Larchmont", "Monarch",
         "Sterling", "Beacon", "Clearwater", "Highgate", "Lakeshore", "Ridgeline", "Summit", "Vantage",
         "Ashford", "Bluewater", "Copperfield", "Draycott", "Eastgate", "Fenwick", "Glenwood", "Halcyon"]
WORD2 = ["", "", "", "Capital", "Global", "Strategic", "Alternative", "Atlantic", "Pacific",
         "Continental", "Heritage", "Legacy", "Pioneer", "Cornerstone", "Evergreen"]


def load_facilities() -> list[tuple[str, str, str]]:
    """(account_number, fund_name, bbdate) for the 68 real facilities + 2 orphan accounts."""
    with FACILITIES_FILE.open(newline="", encoding="utf-8") as fh:
        rows = list(csv.reader(fh))
    out: list[tuple[str, str]] = []
    seen: set[str] = set()
    for r in rows[1:]:
        # Skip blanks and any "Unknown" placeholder rows a prior extract may have written back,
        # and dedup by account — so regenerating after copying output into mock/ stays idempotent.
        if r and r[0].strip() and r[0].strip() != "Unknown" and r[2].strip() and r[2].strip() not in seen:
            seen.add(r[2].strip())
            out.append((r[2].strip(), r[1].strip()))
    out.extend(ORPHAN_ACCOUNTS)
    return out


def money(lo: int, hi: int, step: int = 100_000) -> int:
    return random.randrange(lo, hi, step)


def size_label(measure: str) -> str:
    if measure == "pension":
        return f"${random.uniform(2, 180):.1f}B"
    if measure == "nav":
        return f"${random.uniform(0.4, 12):.1f}B"
    return f"${random.uniform(0.3, 60):.1f}B"        # aum


def rating_triplet(ig: bool) -> tuple[str, str, str]:
    pool = IG_RATINGS if ig else NONIG_RATINGS
    i = random.randrange(len(pool))
    jitter = lambda: pool[min(len(pool) - 1, max(0, i + random.randint(-1, 1)))]
    return jitter(), jitter(), jitter()


def pick_weighted(options, weights):
    return random.choices(options, weights=weights, k=1)[0]


def build_investor(idx: int, used_names: set) -> dict:
    itype = pick_weighted(list(TYPE_WEIGHTS), list(TYPE_WEIGHTS.values()))
    suffixes, measure = TYPE_SPECS[itype]
    while True:
        w2 = random.choice(WORD2)
        base = f"{random.choice(WORD1)}{(' ' + w2) if w2 else ''}"
        name = f"{base} {random.choice(suffixes)}"
        if name not in used_names:
            used_names.add(name)
            break
    ig = random.random() < 0.68
    sp, mdy, fitch = rating_triplet(ig)
    agent_cat, agent_ar = pick_weighted(
        [(c, r) for c, r, _ in AGENT_CATEGORIES], [w for *_, w in AGENT_CATEGORIES])
    lo, hi, _ = pick_weighted(UBS_BANDS, [w for *_, w in UBS_BANDS])
    ubsar = round(random.uniform(lo, hi), 2)
    is_pension = measure == "pension"
    return {
        "name": name,
        "parent": name,
        "spv": "Y" if random.random() < 0.12 else "N",
        "itype": itype,
        "region": random.choice(REGIONS),
        "hq": "Yes" if random.random() < 0.8 else "No",
        "inst": "HNW" if itype == "Family Office" and random.random() < 0.5 else "Institutional",
        "ig": "Yes" if ig else "No",
        "cls": agent_cat,
        "agent_ar": agent_ar,
        "sp": sp, "mdy": mdy, "fitch": fitch,
        "aum": size_label("aum") if measure == "aum" else None,
        "nav": size_label("nav") if measure == "nav" else None,
        "pension": size_label("pension") if is_pension else None,
        "funding": round(random.uniform(0.72, 1.08), 2) if is_pension else None,
        "ubsar": ubsar,
        "agent_cl": round(random.uniform(0.05, 0.15), 2),
        "ubs_cl": round(random.uniform(0.05, 0.15), 2),
    }


def weighted_sample_without_replacement(items, weights, k):
    """Efraimidis-Spirakis: key = U^(1/w); take the k largest keys. No numpy needed."""
    keyed = sorted(((random.random() ** (1.0 / w), it) for it, w in zip(items, weights)), reverse=True)
    return [it for _, it in keyed[:k]]


def main() -> int:
    random.seed(SEED)
    facilities = load_facilities()                    # [(acct, fund), ...]
    base = date(2026, 6, 25)
    # One BBDate per facility, M/D/YYYY (built manually — Windows strftime lacks %-m/%-d).
    fac_bbdate = {}
    for acct, _ in facilities:
        d = base - timedelta(days=random.randint(0, 240))
        fac_bbdate[acct] = f"{d.month}/{d.day}/{d.year}"

    fac_weights = {acct: random.uniform(0.4, 3.2) for acct, _ in facilities}
    fund_by_acct = dict(facilities)
    accts = [a for a, _ in facilities]

    used_names: set = set()
    positions: list[dict] = []        # each dict = one lp_record row (pre-percent)
    per_fac: dict[str, list[dict]] = {a: [] for a in accts}
    investor_count = 0

    while len(positions) < TARGET_ROWS:
        inv = build_investor(investor_count, used_names)
        investor_count += 1
        r = random.randint(REPEAT_MIN, REPEAT_MAX)
        r = min(r, TARGET_ROWS - len(positions))      # trim last LP to land exactly on TARGET
        chosen = weighted_sample_without_replacement(accts, [fac_weights[a] for a in accts], r)
        for acct in chosen:
            commit = money(2_000_000, 500_000_000)
            # Snap uncalled to clean $100K steps (source values are tidy; kept strictly 0<uncalled<commit).
            uncalled = round(commit * random.uniform(0.15, 0.85) / 100_000) * 100_000
            uncalled = min(max(uncalled, 100_000), commit - 100_000)
            called = commit - uncalled
            agent_bb = round(inv["agent_ar"] * uncalled)
            ubs_bb = round(inv["ubsar"] * uncalled)
            row = {
                **inv,
                "acct": acct, "fund": fund_by_acct[acct], "bbdate": fac_bbdate[acct],
                "commit": commit, "called": called, "uncalled": uncalled,
                "called_pct": round(called / commit, 2),
                "agent_bb": agent_bb, "ubs_bb": ubs_bb,
            }
            positions.append(row)
            per_fac[acct].append(row)

    # Second pass: per-facility share percentages.
    for acct, rows in per_fac.items():
        tot_c = sum(r["commit"] for r in rows) or 1
        tot_u = sum(r["uncalled"] for r in rows) or 1
        for r in rows:
            r["pct_commit"] = round(r["commit"] / tot_c, 4)
            r["pct_uncalled"] = round(r["uncalled"] / tot_u, 4)

    # Write the workbook in SRC_COLS order.
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = SHEET_NAME
    ws.append(SRC_COLS)
    for r in positions:
        ws.append([
            r["acct"], r["fund"], r["name"], r["parent"], r["spv"], r["itype"], r["region"], r["hq"],
            r["inst"], r["ig"], r["cls"], "", r["sp"], r["mdy"], r["fitch"],
            r["aum"], r["nav"], r["pension"], r["funding"], r["ubsar"], r["agent_ar"], r["commit"],
            r["pct_commit"], r["called"], r["uncalled"], r["pct_uncalled"], r["called_pct"],
            r["agent_cl"], r["ubs_cl"], r["agent_bb"], r["ubs_bb"], r["bbdate"],
        ])
    EXPORT_OUT.parent.mkdir(parents=True, exist_ok=True)
    wb.save(EXPORT_OUT)

    fac_sizes = sorted(len(v) for v in per_fac.values())
    print(f"wrote {EXPORT_OUT}")
    print(f"  rows (lp_records target)  : {len(positions)}")
    print(f"  distinct LPs (lp_master)  : {investor_count}")
    print(f"  facilities (incl orphans) : {len(accts)}  ({len(ORPHAN_ACCOUNTS)} orphan)")
    print(f"  LPs/facility  min/med/max : {fac_sizes[0]} / {fac_sizes[len(fac_sizes)//2]} / {fac_sizes[-1]}")
    print(f"  avg repeats per LP        : {len(positions)/investor_count:.1f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
